# Kubernetes namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ozdemirozcelik

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comp4016-deployment
  namespace: ozdemirozcelik
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comp4016-app
  template:
    metadata:
      labels:
        app: comp4016-app
    spec:
      containers:
      - name: comp4016-container
        image: ozdemirozcelik/comp4016_2
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VALUE
          value: environmentSnake
        envFrom:
        - configMapRef:
            name: comp4016-app-config
        - secretRef:
            name: comp4016-app-secret

---

# Service with type NodePort
apiVersion: v1
kind: Service
metadata:
  name: comp4016-app-service
  namespace: ozdemirozcelik
spec:
  type: NodePort
  selector:
    app: comp4016-app
  ports:
    - protocol: TCP
      port: 8080  # App listens on this port
      targetPort: 8080  # App runs on this port
      nodePort: 32000 # Expose this port on the nodes

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: comp4016-app-config
  namespace: ozdemirozcelik
data:
  CONFIG_VALUE: snake

---

apiVersion: v1
kind: Secret
metadata:
  name: comp4016-app-secret
  namespace: ozdemirozcelik
data:
  SECRET_VALUE: c2VjcmV0U25ha2U= # Base64-encoded value of 'secretSnake'